# pytorch_lightning==1.9.5
fit:
  model:
    targets_path: artifacts/classes_mean.pkl
    mapping:
      0: 3
      1: 7
      2: 3
      3: 8
      4: 5
      5: 6
      6: 9
      7: 1
      8: 0
      9: 2
