# pytorch_lightning==1.9.5
fit:
  model:
    targets_path: artifacts/classes_mean.pkl
    mapping:
      0: 1
      1: 2
      2: 3
      3: 4
      4: 5
      5: 6
      6: 7
      7: 8
      8: 9
      9: 10
