# pytorch_lightning==1.9.5
fit:
  model:
    net:
      class_path: morphers.net.baseline.BaselineNet
      init_args:
        n_input: $INPUT_DIM
        n_features: $HIDDEN_DIM
        hidden_module: null
        head:
          class_path: torch.nn.Linear
          init_args:
            in_features: $HIDDEN_DIM
            out_features: 10
